var key=CT.getVal("mapkey");CT.scriptImport("https://maps.googleapis.com/maps/api/js"+(key?"?key="+key:""));window.CT=window.CT||{};window.CT.map=window.CT.map||{};window.CT.map.util=window.CT.map.util||{};CT.map.util={_:{keys:[],kindex:0,try_limit:20,llcache:CT.storage.get("addr2latlng")||{},geo_fallback:{lat:37.75,lng:-122.45},get_res:function(addr){var params={address:addr},_=CT.map.util._,k=_.keys[_.kindex];if(k){params.key=k;_.kindex+=1;}else
_.kindex=0;return CT.net.get("https://maps.googleapis.com/maps/api/geocode/json",params,true).results[0];},try_a2ll:function(addr){var tries=0,res,key,_=CT.map.util._;while(tries<_.try_limit&&!res){res=_.get_res(addr);if(res)return res
tries+=1;CT.log("CT.map.util.addr2latlng: can't find "+addr+" - trying again! tries: "+tries);}}},setGeoKeys:function(keys){CT.map.util._.keys=keys;},setGeoFallback:function(pos){CT.map.util._.geo_fallback=pos;},getGeoFallback:function(){return CT.map.util._.geo_fallback;},icon:function(icon,marker){if(icon&&typeof icon=="string"){var orig=marker.getIcon();if(orig&&orig.url)
return CT.merge({url:icon},orig);}
return icon;},latlng:function(position){return position instanceof google.maps.LatLng?position:new google.maps.LatLng(position);},addr2latlng:function(addr){var _=CT.map.util._,c=_.llcache;if(!c[addr]){c[addr]=_.try_a2ll(addr).geometry.location;CT.storage.set("addr2latlng",c);}
return c[addr];},ips2latlngs:function(ips,cb){CT.net.post({path:location.protocol+"//api.mkult.co/geo",params:{action:"ips",ips:ips},cb:cb});},bounds:function(sw,ne){return new google.maps.LatLngBounds(CT.map.util.latlng(sw),CT.map.util.latlng(ne));},distance:function(origin,destination,cb,mode,units){var _=CT.map.util._;if(!_.dservice)
_.dservice=new google.maps.DistanceMatrixService();_.dservice.getDistanceMatrix({origins:[origin],destinations:[destination],travelMode:google.maps.TravelMode[mode||"DRIVING"],unitSystem:google.maps.UnitSystem[units||"IMPERIAL"]},function(resp,status){if(status!="OK")
return alert("distance error: "+status);cb(parseInt(resp.rows[0].elements[0].distance.text));});}};;window.CT.map.Map=window.CT.map.Map||{};CT.map.Map=CT.Class({CLASSNAME:"CT.map.Map",markers:{},addTriggers:function(data,dtype,datacb,newcb,mlist){var marker=this.addMarker;mlist=mlist||CT.dom.id("map"+dtype+"s");newcb&&mlist.appendChild(CT.panel.trigger({"title":"new "+dtype},newcb));CT.panel.triggerList(data.map(function(orig){d=datacb(orig);d.key=orig.key;d.marker=marker(d);return d;}),function(d){d.marker.showInfo();},mlist);},setMarker:function(data){this.addMarker(data).update(data);},addMarker:function(data){var m=this.markers[data.key]=this.markers[data.key]||new CT.map.Marker(data);if(this.map)
m.add(this.map);else
this.opts.markers[data.key]=data;return m;},addMarkers:function(dlist){var that=this,ms=[];dlist.forEach(function(d){ms.push(that.addMarker(d));});return ms;},resizeMarkers:function(w,h){for(var m in this.markers)
this.markers[m].resize(w,h);},clearMarkers:function(markers){(Array.isArray(markers)?markers:Object.values(this.markers)).forEach(function(m){m.remove();});},getMarker:function(key){return this.markers[key];},removeMarker:function(key){var marker=this.getMarker(key);if(marker)
marker.remove();else
this.log("removeMarker(): can't find key '"+key+"'");},geoJson:function(gj){this.map.data.loadGeoJSON(gj);},fit:function(lat1,lng1,lat2,lng2){this.map.fitBounds(CT.map.util.bounds({lat:lat1,lng:lng1},{lat:lat2,lng:lng2}));},frame:function(m1,m2){var p1=m1.getPosition(),p2=m2.getPosition();this.fit(Math.min(p1.lat(),p2.lat()),Math.min(p1.lng(),p2.lng()),Math.max(p1.lat(),p2.lat()),Math.max(p1.lng(),p2.lng()));},autoBounds:function(){var mz=Object.values(this.opts.markers),las=mz.map(function(m){return m.position.lat;}),los=mz.map(function(m){return m.position.lng;}),minla=Math.min.apply(null,las),minlo=Math.min.apply(null,los),maxla=Math.max.apply(null,las),maxlo=Math.max.apply(null,los),midla=(minla+maxla)/2,midlo=(minlo+maxlo)/2;this.log("min",minla,minlo);this.log("max",maxla,maxlo);this.log("mid",midla,midlo);this.opts.center={lat:midla,lng:midlo};return{min:{lat:minla,lng:minlo},max:{lat:maxla,lng:maxlo}};},_build:function(){var k,oz=this.opts,bounds=oz.autoFrame&&this.autoBounds(),bmin=bounds&&bounds.min,bmax=bounds&&bounds.max;this.opts.center=CT.map.util.latlng(this.opts.center);this.map=new google.maps.Map(this.opts.node,this.opts);for(k in this.opts.markers)
this.addMarker(this.opts.markers[k]);if(this.opts.geojson)
this.geoJson(this.opts.geojson);this.refresh();this.map.setCenter(this.opts.center);bounds&&this.fit(bmin.lat,bmin.lng,bmax.lat,bmax.lng);for(k in this.opts.listeners)
this.listen(k,this.opts.listeners[k]);this.opts.onload&&this.opts.onload();},setCenter:function(latlng){this.map.setCenter(latlng);},panTo:function(latlng){this.map.panTo(latlng);},refresh:function(){google.maps.event.trigger(this.map,'resize');},_geoSucceed:function(pos){this.opts.center={lat:pos.coords.latitude,lng:pos.coords.longitude};this._build();},_geoFail:function(){this.opts.center=CT.map.util.getGeoFallback();this._build();},listen:function(evt,cb){google.maps.event.addListener(this.map,evt,cb);},init:function(opts){this.opts=opts=CT.merge(opts,{zoom:12,disableDefaultUI:true,zoomControl:true,autoFrame:false,markers:{},listeners:{}});if(opts.center||opts.autoFrame)
this._build();else
navigator.geolocation.getCurrentPosition(this._geoSucceed,this._geoFail);}});;window.CT.map.Node=window.CT.map.Node||{};CT.map.Node=CT.Class({CLASSNAME:"CT.map.Node",_regEvt:function(evt){if(this.opts.listeners[evt])
google.maps.event.addDomListener(this.content,evt,this.opts.listeners[evt]);},_add:function(){this.content=CT.dom.node(this.opts.content,"div",this.opts.className);this.projection=this.overlay.getProjection();CT.dom.setContent(this.overlay.getPanes().floatPane,this.content);Object.keys(this.opts.listeners).forEach(this._regEvt);},_remove:function(){google.maps.event.clearListeners(this.content);CT.dom.remove(this.content);this.content=null;},_draw:function(){if(!this.content||!this.opts.visible)return;var point=this.projection.fromLatLngToDivPixel(this.opts.position);this.content.style.left=point.x+"px";this.content.style.top=point.y+"px";},getPosition:function(){return this.opts.position;},setPosition:function(latlng){this.opts.position=latlng;this._draw();},setVisible:function(vis){this.opts.visible=vis;if(this.content){this.content.style.display=vis?"block":"none";this._draw();}},setContent:function(content){this.opts.content=content;if(this.content)
CT.dom.setContent(this.content,content);},setListeners:function(listeners){this.opts.listeners=listeners;if(this.content){google.maps.event.clearListeners(this.content);Object.keys(listeners).forEach(this._regEvt);}},clearListeners:function(){this.setListeners({});},addListener:function(evt,listener){this.opts.listeners[evt]=listener;this._regEvt(evt);},addUpdater:function(property,cb){this.opts.updaters[property]=cb;},update:function(opts){var o=this.opts=CT.merge(opts,this.opts);if("visible"in opts)
this.setVisible(opts.visible);if(opts.position)
this.setPosition(opts.position);if(opts.content)
this.setContent(opts.content);if(opts.listeners)
this.setListeners(opts.listeners);Object.keys(o.updaters).forEach(function(uprop){if(uprop in opts)
o.updaters[uprop](opts[uprop]);});},show:function(){this.overlay.setMap(this.opts.map);},hide:function(){this.overlay.setMap(null);},init:function(opts){this.opts=opts=CT.merge(opts,{visible:true,updaters:{},listeners:{}});this.overlay=new google.maps.OverlayView();this.overlay.onAdd=this._add;this.overlay.onRemove=this._remove;this.overlay.draw=this._draw;}});;window.CT.map.Marker=window.CT.map.Marker||{};CT.map.DOMMarker=CT.Class({CLASSNAME:"CT.map.DOMMarker",setTitle:function(title){this.opts.title=title;if(this.title)
this.title.setContent(title);else
this._build();},setIcon:function(icon){if(typeof icon=="string")
icon=CT.dom.img(icon);this.setContent(icon);},setMap:function(map){this.opts.map=map;this.overlay.setMap(map);},_build:function(){if(this.opts.title){this.title=new CT.map.Node(CT.merge(this.opts.hover,{map:this.opts.map,content:this.opts.title,position:this.getPosition(),className:"tooltip"}));}},init:function(){this.opts=CT.merge(this.opts,{className:"abs pointer"});this.addUpdater("map",this.setMap);this.addUpdater("icon",this.setIcon);this.addUpdater("title",this.setTitle);this._build();}},CT.map.Node);CT.map.infoWindow=function(){return new google.maps.InfoWindow();};CT.map.infoWindowSingleton=function(){if(!CT.map._iw)
CT.map._iw=CT.map.infoWindow();return CT.map._iw;};CT.map.useSingleInfoWindow=function(){CT.map._iwSingleton=true;};CT.map.Marker=CT.Class({CLASSNAME:"CT.map.Marker",_wrappers:["title","icon","map","content","position","visible"],_converters:{position:CT.map.util.latlng,icon:CT.map.util.icon},add:function(map){this.opts.map=map;this.marker.setMap(map);},remove:function(){this.opts.map=null;this.marker.setMap(null);this.hideInfo();},update:function(opts){var thiz=this;this.opts=CT.merge(opts,this.opts);this._wrappers.forEach(function(w){if(w in thiz.opts)
thiz["set"+CT.parse.capitalize(w)](thiz.opts[w]);});},resize:function(w,h){h=h||w;this.setIcon(CT.merge({size:new google.maps.Size(w,h)},this.getIcon()));},_showInfo:function(){this.cancelInfo();var iw=this._infoWindow=this._infoWindow||CT.map.infoWindow();iw.setContent(this.opts.info);iw.setPosition(this.getPosition());iw.open(this.opts.map);},showInfo:function(){if(this.opts.infoDelay){if(!this._infoTimeout)
this._infoTimeout=setTimeout(this._showInfo,this.opts.infoDelay);}else
this._showInfo();},cancelInfo:function(){if(this._infoTimeout){clearTimeout(this._infoTimeout);delete this._infoTimeout;}},hideInfo:function(){this._infoWindow&&this._infoWindow.close();},_wrap:function(k){var m=this,kup=CT.parse.capitalize(k);this["get"+kup]=function(){return m.opts[k];};this["set"+kup]=function(val){m.opts[k]=m._converters[k]?m._converters[k](val,m):val;m.marker["set"+kup](m.opts[k]);};},_buildWrappers:function(){this._wrappers.forEach(this._wrap);},_addMarkerListener:function(evt,cb){google.maps.event.addListener(this.marker,evt,cb);},_buildMarker:function(){this.marker=new google.maps.Marker(this.opts);for(var evt in this.opts.listeners)
this._addMarkerListener(evt,this.opts.listeners[evt]);},_buildCustomMarker:function(){this.marker=new CT.map.DOMMarker(this.opts);},init:function(opts){this.opts=opts=CT.merge(opts,{icon:"http://maps.google.com/mapfiles/ms/icons/purple-dot.png"});if(opts.info)
opts.listeners=CT.merge(opts.listeners,{click:this.showInfo});opts.position=CT.map.util.latlng((opts.position&&opts.position.lat&&opts.position.lng)?opts.position:CT.map.util.addr2latlng(opts.address));opts.content?this._buildCustomMarker():this._buildMarker();if(CT.map._iwSingleton)
this._infoWindow=CT.map.infoWindowSingleton();this._buildWrappers();if(this.opts.map)
this.add(this.opts.map);}});;window.CT.map.Shape=window.CT.map.Shape||{};CT.map.Shape=CT.Class({CLASSNAME:"CT.map.Shape",_gclass:function(){var cname=this.CLASSNAME.split(".")[2];return{Shape:"Polygon",Line:"Polyline"}[cname]||cname;},add:function(map){this.opts.map=map;this.shape.setMap(map);},remove:function(){this.opts.map=null;this.shape.setMap(null);},init:function(opts){this.opts=opts;this.shape=new google.maps[this._gclass()](opts);if(opts.map)
this.add(opts.map);}});CT.map.Circle=CT.Class({CLASSNAME:"CT.map.Circle"},CT.map.Shape);CT.map.Rectangle=CT.Class({CLASSNAME:"CT.map.Rectangle"},CT.map.Shape);CT.map.Line=CT.Class({CLASSNAME:"CT.map.Line"},CT.map.Shape);;window.CT.map.Panorama=window.CT.map.Panorama||{};CT.map.Panorama=CT.Class({CLASSNAME:"CT.map.Panorama",rotate:function(diff){this.opts.pov.heading+=diff;this.pan.setPov(this.opts.pov);},tilt:function(diff){this.opts.pov.pitch+=diff;this.pan.setPov(this.opts.pov);},zoom:function(z){this.opts.zoom=z;this.pan.setZoom(z);},shift:function(lnum){this.pan.setPano(this.pan.getLinks()[lnum||0].pano);},_move:function(data,status){if(status=="OK")
this.pan.setPano(data.location.pano);else
this.log("move failed!",status);},move:function(coords,as_diffs){if(as_diffs){this.opts.position={lat:this.pan.position.lat(),lng:this.pan.position.lng()};for(var axis in coords)
this.opts.position[axis]+=coords[axis];}else
this.opts.position=coords;this.service.getPanorama({radius:50,location:this.opts.position},this._move);},update:function(opts){this.opts=CT.merge(opts,this.opts);if(opts.position)
this.move(opts.position);if(opts.pano)
this.pan.setPano(opts.pano);if(opts.pov)
this.pan.setPov(opts.position);if(opts.zoom)
this.pan.setZoom(opts.zoom);},init:function(opts){this.opts=opts=CT.merge(opts,{cbs:{},pov:{pitch:0,heading:0},node:document.body});this.service=new google.maps.StreetViewService();var pan=this.pan=new google.maps.StreetViewPanorama(opts.node,opts);setTimeout(function(){for(var event_name in opts.cbs)
pan.addListener(event_name,opts.cbs[event_name]);},2000);}});;;